node {
    
    stage('Git Clone') { 
        git branch: 'main', url: 'https://github.com/soundaryacs/terraform-cicd.git'
    }

    stage('Terraform Init') {
        dir('Day-01-DIR') {
            sh 'terraform init'
        }
    }

    stage('Terraform Plan') {
        dir('Day-01-DIR') {
            sh 'terraform plan'
        }
    }

    stage('Terraform Apply') {
        dir('Day-01-DIR') {
            sh 'terraform destroy -auto-approve'
        }
    }
}
